openapi: 3.0.1

info:
  title: ainize-catoonize-swagger
  description: |
    Convert images and videos into a cartoon style
    ---
      How to use:
      * Select a file Type
      * upload a file
      * Execute and wait little time
  contact:
    name: Ainizer - Sangil Park
  version: "0.1"
  license:
    name: "Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
    url: https://github.com/pool-limited/cartoonize#license

servers:
  - url: https://main-cartoonize-pool-limited.endpoint.ainize.ai/

paths:
  /predict:
    post:
      requestBody:
        required: true
        description: "Convert images and videos into a cartoon style"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file_type:
                  type: string
                  enum: [image, video]
                source:
                  type: string
                  format: binary
            encoding:
              files:
                contentType: image/*, video/*

      responses:
        '200':
          description: success
          content:
            image/jpg:
              schema:
                type: string
                format: binary
            video/mp4:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request

        '500':
          description: Server side error
